### ISSUE TITLE
FP-16 training failure

### ISSUE THREAD

**Issue by kannadaraj** [jinhan/tacotron2-gst#3]
Hello @jinhan ,

  Thanks for sharing such great repo. _ was trynign to train in fp16. But it gives me following error. Please can you help me fix it.. Thanks.. I ahve enablep16 training.

Command: `python -m multiproc train.py --output_directory=outdir --log_directory=logdir`

```
Traceback (most recent call last):

  File "train.py", line 285, in <module>

    args.warm_start, args.n_gpus, args.rank, args.group_name, hparams)

  File "train.py", line 222, in train

    optimizer.backward(loss)
    
  File "/projects/playground/tacotron2-gst/fp16_optimizer.py", line 362, in backward

    self.loss_scaler.backward(loss.float())
    
  File "/projects/playground/tacotron2-gst/loss_scaler.py", line 80, in backward

    scaled_loss.backward()
    
  File "/pyenvs/taco/lib/python3.6/site-packages/torch/tensor.py", line 118, in backward

    torch.autograd.backward(self, gradient, retain_graph, create_graph)
    
  File "/pyenvs/taco/lib/python3.6/site-packages/torch/autograd/__init__.py", line 93, in backward

    allow_unreachable=True)  # allow_unreachable flag

  File "/projects/playground/tacotron2-gst/distributed.py", line 157, in allreduce_params

    coalesced = _flatten_dense_tensors(grads)
    
  File "/projects/playground/tacotron2-gst/distributed.py", line 19, in _flatten_dense_tensors
    
    flat = torch.cat([t.contiguous().view(-1) for t in tensors], dim=0)

RuntimeError: Expected object of scalar type Half but got scalar type Float for sequence element 3 in sequence argument at position #1 'tensors'

    ```

**Comment by jinny1208** [comment]
Hello, just wondering, but did you solve the problem? I, too, am having trouble (albeit a bit different) with using fp16.
